# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dGnome/Code/College/EmbbedDes/EEEN40280-SystemOnChip/Hardware/DemoSystem.srcs/sources_1/ip/blk_mem_4Kword/blk_mem_4Kword.xci
# IP: The module: 'blk_mem_4Kword' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dGnome/Code/College/EmbbedDes/EEEN40280-SystemOnChip/Hardware/DemoSystem.srcs/sources_1/ip/blk_mem_4Kword/blk_mem_4Kword_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_4Kword'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dGnome/Code/College/EmbbedDes/EEEN40280-SystemOnChip/Hardware/DemoSystem.srcs/sources_1/ip/blk_mem_4Kword/blk_mem_4Kword.xci
# IP: The module: 'blk_mem_4Kword' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dGnome/Code/College/EmbbedDes/EEEN40280-SystemOnChip/Hardware/DemoSystem.srcs/sources_1/ip/blk_mem_4Kword/blk_mem_4Kword_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_4Kword'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
